### ISSUE TITLE
Use of built-in Math's function

### ISSUE THREAD

**Issue by mohammedShabib01** [mohammedShabib01/SQA22F23292#1]
can you please help me to find the exponent of a given number by using built-in functions in C programming language???

**Comment by mohamed97979** [comment]
Yeah Sure! You can use the following code to find the exponent of a given number by using the built-in function in C programming language.

#include <math.h>
#include <stdio.h>

int main() {
    double base, exp, result;
    printf("Enter a base number: ");
    scanf("%lf", &base);
    printf("Enter an exponent: ");
    scanf("%lf", &exp);

    // calculates the power
    result = pow(base, exp);

    printf("%.1lf^%.1lf = %.2lf", base, exp, result);
    return 0;
}
